import "jquery";
import "popper.js";
import "./js/jquery.maskedinput.min";
import "./js/preloader";
import "./js/scrollToId";
import "./js/checkDevice";
import "./js/successful";
import "./js/listDevices";
import "./js/modalForm";